### ISSUE TITLE
Migrate to PHP 8.1.0

### ISSUE THREAD

**Issue by Machou** [ip2location/ip2proxy-php#10]
With PHP 8.1.0 i have this error's :

```PHP Warning:  Undefined array key 10 in /home/blok/composer/vendor/ip2location/ip2proxy-php/src/Database.php```

```PHP Deprecated:  substr(): Passing null to parameter #2 ($offset) of type int is deprecated in /home/blok/composer/vendor/ip2location/ip2proxy-php/src/Database.php```

Lines :

1321
1329
1330
1353
1348
1371
1376
1399
1417
1422
1440
1445
1463
1468
1486
1491
1509
1514
1532
1537
1555
1560

**Comment by ip2location** [comment]
Can you try with the version [4.1.0](https://github.com/ip2location/ip2proxy-php/releases/tag/4.1.0)?

**Comment by Machou** [comment]
I have download the latest version :

DB11.LITE IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE
https://lite.ip2location.com/download?id=10

Errors :

```bash
PHP Fatal error:  Uncaught Exception: IP2Proxy\\Database: Incorrect IP2Proxy BIN file format. Please make sure that you are using the latest IP2Proxy BIN file. in /home/blok/composer/vendor/ip2location/ip2proxy-php/src/Database.php:657
Stack trace:
/home/blok/www/cfg/class.grab.php(73): IP2Proxy\\Database->__construct('geo/IP2LOCATION...', 100001)
/home/blok/www/exemple.php(6): Grab->get_infos()
/home/blok/www/index.php(5): require_once('/home/blok/www/...')
{main}
thrown in /home/blok/composer/vendor/ip2location/ip2proxy-php/src/Database.php on line 657
```

But work with this file : IP2LOCATION-LITE-DB11.BIN

**Comment by chrislim2888** [comment]
You should use IP2Proxy BIN file, but not IP2Location. You can download the file at https://lite.ip2location.com/ip2proxy-lite

**Comment by Machou** [comment]
I'm connected on the website, when i want download file i have 404 :P

**Comment by Machou** [comment]
I don't understand the difference between the two files LOCATION and PROXY, they are the same information, right?

Concerning version 11, I have a 404, IP V4 and IP V6 for the 10 it works.

Thanks =)

**Comment by ip2location** [comment]
It's not the same. Please download the IP2Proxy database at https://lite.ip2location.com/database/px11-ip-proxytype-country-region-city-isp-domain-usagetype-asn-lastseen-threat-residential-provider

**Comment by Machou** [comment]
> It's not the same. Please download the IP2Proxy database at https://lite.ip2location.com/database/px11-ip-proxytype-country-region-city-isp-domain-usagetype-asn-lastseen-threat-residential-provider

Page Not Found
404

Oops! I have eaten that file...

**Comment by ip2location** [comment]
Can you try to login and download again?

Or you can download it from https://lite.ip2location.com/database-download under "IP2Proxy Database" tab.

**Comment by Machou** [comment]
> Can you try to login and download again?
> 
> Or you can download it from https://lite.ip2location.com/database-download under "IP2Proxy Database" tab.

Everything seems to work.

But could you explain what is the difference between IP2PROXY and IP2LOCATION?

Regards

**Comment by ip2location** [comment]
The IP2Proxy database contains only the IP range that has been detected as a proxy server.

While IP2Location database contains the IP range of the world, with geolocation information with it.
