### ISSUE TITLE
Hello! i am having bugs in php8.0 the output error i can see is this. Some help?

### ISSUE THREAD

**Issue by jmads1** [ip2location/ip2proxy-php#11]
I paste here the production output text:

`"Non-static method IP2Proxy\Database::wrap32() cannot be called statically" at /.../vendor/ip2location/ip2proxy-php/src/Database.php line 1238 {"exception":"[object] (Error(code: 0): Non-static method IP2Proxy\\Database::wrap32() cannot be called statically at /.../vendor/ip2location/ip2proxy-php/src/Database.php:1238)"`

**Comment by ip2location** [comment]
I'm not able to reproduce the issue on PHP 7.4.26, 8.0.14 or 8.1.0.

Please share you configuration and steps to reproduce the error.

**Comment by batnieluyo** [comment]
@ip2location its on PHP 8.1.5
