### ISSUE TITLE
IPV6 ADDRESS MISSING IN IPV4 BIN

### ISSUE THREAD

**Issue by LinuXperia** [ip2location/ip2proxy-php#13]
Hi.
I am having a huge amount of this errors here in my logs !

> [client 2402:8100:206b:61ba:3ff5:70b7:b783:e457:13514] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: IPV6 ADDRESS MISSING IN IPV4 BIN in /var/www/vhosts/mywebsite/ssd-storage/index.php on line 1168

> [client 2409:4070:2cbb:a797::d4a:ac01:22192] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: IPV6 ADDRESS MISSING IN IPV4 BIN in /var/www/vhosts/mywebsite/ssd-storage/index.php on line 1168

...

Just some examples of IPv6 Adresses 
`2402:8100:206b:61ba:3ff5:70b7:b783:e457`
`2409:4070:2cbb:a797::d4a:ac01`
`2a02:27b0:4d06:380:f889:7df8:f9c9:3312`
`2409:4066:e06:68f6::e908:340d`
`2001:67c:2628:647:d::37b`
`2607:fb90:cf0:20::4`
`2402:3a80:574:885:0:b:f891:c001`
`2806:1000:8004:6c46:2462:e141:a494:25c4`
`2401:4900:2e94:c30b:0:69:eb10:d501`
`2600:6c60:577f:e7ab:e57f:e1bc:8495:9931`
`2401:4900:129b:7526:857b:d74:2970:a3f6`
`2409:4073:4d8c:71dc::b1c8:7f15`
`2405:201:a004:416b:b947:722b:39b2:8501`
`2a02:2149:8625:1600:2408:c2b7:e40d:ba64`
that makes problem with IP2Location and PHP and create huge amount of error log entrys.

It may help others too if this errorors get fixed.
I ma using the newest IP2LOCATION-LITE-DB1.BIN released 01. June 2022
Thanks a lot.
Best Regards LinuXperia

**Comment by ip2location** [comment]
Please download the IPV6 BIN if you are lookup for both IPV4 and IPV6 IP addresses. The file name is IP2LOCATION-LITE-DB1.IPV6.BIN.
