### ISSUE TITLE
No results with new databases

### ISSUE THREAD

**Issue by belajh** [ip2location/ip2proxy-php#15]
Hi,

With the sample database (https://cdn.ip2location.com/downloads/sample.bin.px11.zip) the library works fine.

Package: PX11
Database Date: 2021.5.28
$records = $db->lookup('1.0.0.8', \IP2PROXY\Database::ALL);
Array
(
    [ipNumber] => 16777224
    [ipVersion] => 4
    [ipAddress] => 1.0.0.8
    [countryName] => United States of America
    [countryCode] => US
    [provider] => CloudFlare
    [threat] => -
    [lastSeen] => 22
    [as] => CLOUDFLARENET
    [asn] => 13335
    [usageType] => CDN
    [domain] => cloudflare.com
    [proxyType] => DCH
    [isProxy] => 2
    [isp] => APNIC and CloudFlare DNS Resolver Project
    [cityName] => Los Angeles
    [regionName] => California
)

However with the up date database,  the library returns empty response for all IP without any error message.

Package: PX11
Database Date: 2023.9.1
$records = $db->lookup('1.0.0.8', \IP2PROXY\Database::ALL);
Array
(
    [ipNumber] => 16777224
    [ipVersion] => 4
    [ipAddress] => 1.0.0.8
    [countryName] => -
    [countryCode] => -
    [provider] => -
    [threat] => -
    [lastSeen] => -
    [as] => -
    [asn] => -
    [usageType] => -
    [domain] => -
    [proxyType] => -
    [isProxy] => 0
    [isp] => -
    [cityName] => -
    [regionName] => -
)

Anyone else experienced this error?

**Comment by ip2location** [comment]
May I know where did you download the "up date" database? Are you referring to the commercial database updated daily?

**Comment by belajh** [comment]
> May I know where did you download the "up date" database? Are you referring to the commercial database updated daily?

Sorry I mean up to date database.
I have downloaded it from https://lite.ip2location.com/download?id=53

**Comment by ip2location** [comment]
IP2Location LITE database consists of open proxy (PUB) records only. It does not contain data center ranges like the row you found missing. However, the row is available in the commercial database.

**Comment by belajh** [comment]
> IP2Location LITE database consists of open proxy (PUB) records only. It does not contain data center ranges like the row you found missing. However, the row is available in the commercial database.

Thanks for the explanation.
