### ISSUE TITLE
shmop_close function has been DEPRECATED as of PHP 8.0.0

### ISSUE THREAD

**Issue by spaitnet** [ip2location/ip2proxy-php#16]
https://github.com/ip2location/ip2proxy-php/blob/f8a99a93b1ff91e1b091f1ddc4115c1801b43e70/src/Database.php#L584C8-L584C8
Add
`if (PHP_MAJOR_VERSION < 8) {
	shmop_close($shmId);
}`

**Comment by ip2location** [comment]
#17 https://github.com/ip2location/ip2proxy-php/commit/5696b0658888af22047fa9d34d65fff518e853cd
