### ISSUE TITLE
Call to undefined function IP2Proxy\bcadd() in IP2Proxy\Database::ipVersionAndNumber()

### ISSUE THREAD

**Issue by ennorehling** [ip2location/ip2proxy-php#4]
I noticed today that class.IP2Proxy.php depends on the bcmath functions bcadd and bcmul. Those are optional, and our production site didn't have them installed, causing the error message above.

The code should probably check for function_exists('bcadd') before using it, and print a clear error message about this?

**Comment by ip2location** [comment]
We have added this checking. Thanks.

**Comment by hayzem** [comment]
`mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined function IP2Location\\bcadd() in /.../wp-content/plugins/ip2location-redirection/class.IP2Location.php:995, referer: https://www.google.com/`

`
DB File: IP2LOCATION-LITE-DB1.BIN
Updated At: 2019-12-28
`

We are seeing this error in the logs.

**Comment by BassemN** [comment]
@hayzem make sure to install `bcmath` PHP extension
